{{- if .Values.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "tofu-controller.fullname" . }}-metrics-service
  labels:
    {{- include "tofu-controller.labels" . | nindent 4 }}
spec:
  ports:
  - port: 8080
    name: metrics
    protocol: TCP
    targetPort: 8080
  selector:
    {{- include "tofu-controller.selectorLabels" . | nindent 4 }}
  sessionAffinity: None
  type: ClusterIP
{{- end -}}